config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

#root as home
root 'wellcome#home'
get 'about', to: 'wellcome#about'

resources :articles

get 'signup', to: 'users#new'
resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord:: Base
	belongs_to :user
	validates :title,presence:true,length:{minimum:3,maximum:50}
	validates :description,presence:true,length:{minimum:10,maximum:300}
	validates :user_id, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
	has_secure_password
	before_save { self.email = email.downcase }
	validates :username, presence: true, 
				uniqueness: { case_sensitive: false }, 
				length:{ minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum:105 },
				uniqueness: { case_sensitive:false },
				format:{ with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#article find method is calling here first time before any action
	before_action :set_article, only: [:edit,:update,:show,:destroy]

	#index action method
	def index
		@articles = Article.paginate(page: params[:page], per_page: 2)
	end

	#new action method
	def new
		@article = Article.new
	end

	#create action method
	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
			flash[:success] = "Article Was Successfully Created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	#edit action method
	def edit
		#this method calls above -> @article = Article.find(params[:id])
	end

	#update action method
	def update
		#this method calls above -> @article = Article.find(params[:id])
		if @article.update(article_params)
			flash[:success]= "Article was successfully Updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	#delete action method
	def destroy
		#this method calls above -> @article = Article.find(params[:id])
		@article.destroy
		flash[:danger]="Article was successfully Deleted"
		redirect_to articles_path
	end

	#show action method
	def show
		#this method calls above -> @article = Article.find(params[:id])
	end

	private
		def set_article
			@article = Article.find(params[:id])
		end
		def article_params
			params.require(:article).permit(:title,:description)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#usr find method is calling every time when function call
	before_action :set_user,only: [:edit,:update,:show,:destroy]
	def index
		@users = User.paginate(page: params[:page], per_page: 2)
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "wellcome to the alpha blog #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def edit
		# this method call above first time when start -> @user = User.find(params[:id])
	end
	def update
		# this method call above first time when start -> @user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success] = "Your Profile was Updated Successfully"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		# this method call above first time when start -> @user = User.find(params[:id])
		@users_articles = @user.articles.paginate(page: params[:page], per_page: 2)
	end

	def destroy
		#this method calls above -> @article = Article.find(params[:id])
		@user.destroy
		flash[:danger]="User was successfully Deleted"
		redirect_to articles_path
	end

	private
	def user_params
		params.require(:user).permit(:username,:email,:password)
	end

	def set_user
			@user = User.find(params[:id])
	end
end

app/controllers/wellcome_controller.rb
class WellcomeController <ApplicationController
	#home Action Method
	def home

	end

	#About Action Method
	def about
		
	end
end	

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url , alt: user.username, class: "img-circle")
	end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="article-title">
				<%= link_to article.title,article_path(article)%>
			</div>
			<div class="article-body">
				<%= truncate(article.description,length:100)%>
				<div class = 'article-meta-details'>
						<small>Created By: <%= article.user.username if article.user %>,
								<%= time_ago_in_words(article.created_at)%> ago,
							Last Updated: <%= time_ago_in_words(article.updated_at)%>ago
						</small>
				</div>
			</div>
			<div class="article-actions">
				<%= link_to "Edit this Article",edit_article_path(article),class:"btn btn-xs btn-primary"%>
				<%= link_to "Delete this Article",article_path(article),method: :delete,
				data:{confirm:"Are you sure you want to delete the article?"},class:"btn btn-xs btn-danger"%>
			</div>
		</div>
	</div>
</div>

	<%end%>
</table>

app/views/articles/_form.html.erb
<!------------------------rendering errors partials------------------------------>
<!-- obj here refering to article as passing argument (obj => article) -->
<%= render "shared/errors", obj: @article%>

<!------------------------Form Area------------------------------------->


<div class ='row'>
	<div class='col-xs-12'>
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<!------------------------Title------------------------------------->
			<!--Title label Area-->
			<div class='form-group'>
				<div class= 'control-label col-sm-2'>
					<%= f.label :title %>
				</div>
			<!--Title Text field Area-->
				<div class='col-sm-8'>
					<%= f.text_field :title, class:"form-control", placeholder:"Enter Title", autofocus: true%>
				</div>
			</div>
<!------------------------description--------------------------------->
			<!--Desc label -->
			<div class='form-group'>
				<div class= 'control-label col-sm-2'>
					<%= f.label :description %>
				</div>

				<!--Desc text Area-->
				<div class='col-sm-8'>
					<%= f.text_area :description, rows:10, class:"form-control", placeholder:"Enter Description", autofocus:true %>
				</div>
			</div>
<!------------------------Submit Button--------------------------------->
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<%= f.submit 'Submit', class: 'btn btn-primary btn-lg' %>	
					</div>
				</div>

		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to "Cancel Request and return To Articles",articles_path%> ]
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align = "center">Listing All Articles Details</h1>

<%= render 'article', obj: @articles %>

<div align = "center">
	<%= will_paginate @articles%>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create An Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">
	Title: <%= @article.title %>
</h2>
<div class="well col-xs-8 col-xs-offset-2">
<% if @article.user %>
	<ul class ="listing">
		<div class= "row center">
			<div class ="col-md-4 col-md-offset-4">
				<li>Created By:</li>
				<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
				<li class ="article-title">
					<%= link_to @article.user.username, user_path(@article.user) %>
				</li>
				<li>
					<small>
						<%= pluralize(@article.user.articles.count,'article') if @article.user.articles %>
							
					</small>
				</li>
			</div>
		</div>
	</ul>
<% end %>



	<h4 class="center description"><strong>Description:</strong></h4>
	<hr/>
	<%= simple_format(@article.description) %>
	<div class="article-actions">
		<%= link_to "Edit this Article",edit_article_path(@article),class:"btn btn-xs btn-primary"%>
		<%= link_to "Delete this Article",article_path(@article),method: :delete,
		data:{confirm:"Are you sure you want to delete the article?"},class:"btn btn-xs btn-danger"%>
		<%= link_to "View all Articles",articles_path,class:"btn btn-xs btn-success"%>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class ='container'>
	<footer class='footer'>
		<small>
			Copyright &copy; <a href="https://www.udemy.com">The Complete Ruby on Rails Developer</a>
			by <a href="#">Danial Asghar</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About",about_path%></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
 <!--flash messages alert for success and destroy scenarios -->
  <div class="row">
  	<div class="col-xs-10 col-xs-offset-1">
  		 <% flash.each do |name,msg| %>
  		 <div class='alert alert-<%="#{name}" %>' >
  		 	<a href="#" class="close" data-dismiss="alert">&#215</a>
  		 	<%= content_tag :div,msg,:id => "flash_#{name}" if msg.is_a?(String) %>
  		 </div>
  		  <% end %>
  	</div>
  </div>
  
    <!-- -->

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog",root_path,class:"navbar-brand",id:"logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles",articles_path%></li>
        <li><%= link_to "New Article",new_article_path%></li>
        <li><%= link_to "About",about_path%></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

   <%= render 'layouts/messages' %>
     <div class="container">
      <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
      <div class='debug_container'>
        Path: /layouts/Application
        <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<!------------------------Error messages Area------------------------------------->
<!-- obj here refering to article as passing argument (obj => article) -->
<% if obj.errors.any? %>
	<div class="row">
		<div class ="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count,"error") %>
						prohibited this article from being saved:
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
							<li>
								<%= msg %>	
							</li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>	
	</div>
<% end %>

app/views/users/_signup_form.html.erb
<!------------------------rendering errors partials------------------------------>
<!-- obj here refering to article as passing argument (obj => user) -->
<%= render "shared/errors", obj: @user %>

<!------------------------Form Area------------------------------------->


<div class ='row'>
	<div class='col-xs-12'>
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<!------------------------Username------------------------------------->
			<!--Title label Area-->
			<div class='form-group'>
				<div class= 'control-label col-sm-2'>
					<%= f.label :username %>
				</div>
			<!--Title Text field Area-->
				<div class='col-sm-8'>
					<%= f.text_field :username, class:"form-control", placeholder:"Enter Username", autofocus: true%>
				</div>
			</div>
<!------------------------Email--------------------------------->
			<!--Email label -->
			<div class='form-group'>
				<div class= 'control-label col-sm-2'>
					<%= f.label :email %>
				</div>

				<!--email field area-->
				<div class='col-sm-8'>
					<%= f.email_field :email,  class:"form-control", placeholder:"Enter Your Email", autofocus:true %>
				</div>
			</div>
<!------------------------Password--------------------------------->
			<!--password label -->
			<div class='form-group'>
				<div class= 'control-label col-sm-2'>
					<%= f.label :password %>
				</div>

				<!--password field area-->
				<div class='col-sm-8'>
					<%= f.password_field :password,  class:"form-control", placeholder:"Enter Your Password", autofocus:true %>
				</div>
			</div>
<!------------------------Submit Button--------------------------------->
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<%= f.submit(@user.new_record? ? 'Sign Up': 'Update Account', class: 'btn btn-primary btn-lg') %>	
					</div>
				</div>

		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to "Cancel Request and return To Articles",articles_path%> ]
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1 align = "center">Edit Users Page</h1>
<%= render 'signup_form' %>

app/views/users/index.html.erb
<h1 align='center'> All Alpha Bloggers </h1>

<div align='center'>
	<% @users.each do |user| %>
	<ul class ="listing">
		<div class= "row">
			<div class ="well col-md-4 col-md-offset-4">
				<li><%= link_to gravatar_for(user), user_path(user) %></li>
				<li class ="article-title">
					<%= link_to user.username, user_path(user) %>
				</li>
				<li>
					<small>
						<%= pluralize(user.articles.count,'article') if user.articles %>
							
					</small>
				</li>
			</div>
		</div>
	</ul>
<% end %>
	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align = "center"> SignUp For Alpha Blog </h1>
<%= render 'signup_form'%>

app/views/users/show.html.erb
<h1 align="center">
	Wellcome to  <%= @user.username %>'s page'
</h1>
<div class = 'row'>
	<div class = 'col-md-4 col-md-offset-4 center'>
		<%= gravatar_for @user %>
	</div>
</div>

<h4 align ="center"><%= @user.username %>'s articles'</h4> 

<%= render 'articles/article',obj: @users_articles %>
<%= will_paginate @users_articles %>

app/views/wellcome/about.html.erb
<h1>About Page</h1>


<!-- Link to Home Page -->
<%= link_to "Home", root_path %>

app/views/wellcome/home.html.erb
<div class= "center jumbotron">
	<h1>ALPHA BLOG</h1>
	<%= link_to "Sign Up",signup_path,class:"btn btn-danger btn-lg btn-xlarge"%>
</div>

<!-- Link to About Page -->